[OSEv3:vars]

###########################################################################
### Ansible Vars
###########################################################################
timeout=60
ansible_become=yes
ansible_ssh_user=root

###########################################################################
### OpenShift Basic Vars
###########################################################################

deployment_type=openshift-enterprise
containerized=false
debug_level=2
openshift_release=v3.7

# default project node selector
osm_default_node_selector='env=infra'


###########################################################################
### OpenShift Optional Vars
###########################################################################

# Enable cockpit
osm_use_cockpit=true
osm_cockpit_plugins=['cockpit-kubernetes']

###########################################################################
### OpenShift Master Vars
###########################################################################
openshift_master_api_port=443
openshift_master_console_port=443
openshift_master_cluster_method=native
openshift_master_cluster_hostname=104.211.154.71
openshift_master_cluster_public_hostname=104.211.154.71
openshift_master_default_subdomain=apps.104.211.154.71.xip.io
openshift_master_overwrite_named_certificates=True
#openshift_set_hostname=False
openshift_docker_insecure_registries=30.30.0.0/16
openshift_disable_check=docker_image_availability,disk_availability,docker_storage,memory_availability

###########################################################################
### OpenShift Network Vars
###########################################################################
osm_cluster_network_cidr=10.1.0.0/16
openshift_portal_net=30.30.0.0/16

#os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
os_sdn_network_plugin_name='redhat/openshift-ovs-subnet'

###########################################################################
### OpenShift Authentication Vars
###########################################################################
# htpasswd auth
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# Defining htpasswd users
# openshift_master_htpasswd_users={'user1': '<pre-hashed password>', 'user2': '<pre-hashed password>'}
# or
openshift_master_htpasswd_file=/root/htpasswd.openshift

###########################################################################
### OpenShift Metrics Vars
###########################################################################

openshift_hosted_metrics_deploy=True
openshift_hosted_metrics_storage_kind=nfs
openshift_hosted_metrics_storage_access_modes=['ReadWriteOnce']
openshift_hosted_metrics_storage_nfs_directory=/srv/nfs
openshift_hosted_metrics_storage_nfs_options='*(rw,root_squash)'
openshift_hosted_metrics_storage_volume_name=metrics
openshift_hosted_metrics_storage_volume_size=5Gi
openshift_metrics_hawkular_nodeselector={"env":"infra"}
openshift_metrics_cassandra_nodeselector={"env":"infra"}
openshift_metrics_heapster_nodeselector={"env":"infra"}
openshift_hosted_metrics_public_url=https://hawkular-metrics.apps.104.211.154.71.xip.io/hawkular/metrics

###########################################################################

### OpenShift Router and Registry Vars
###########################################################################

openshift_hosted_router_selector='env=infra'
openshift_hosted_router_replicas=1

openshift_hosted_registry_selector='env=infra'
openshift_hosted_registry_replicas=1
openshift_hosted_registry_storage_kind=nfs
openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
openshift_hosted_registry_storage_nfs_directory=/srv/nfs
openshift_hosted_registry_storage_nfs_options='*(rw,root_squash)'
openshift_hosted_registry_storage_volume_name=registry
openshift_hosted_registry_storage_volume_size=10Gi


###########################################################################
#### OpenShift Host Vars
############################################################################

[OSEv3:children]
masters
etcd
nodes
nfs

[masters]
104.211.154.71

[etcd]
104.211.154.71

[nodes]
104.211.154.71
104.211.154.71 openshift_node_labels="{'logging':'True', 'openshift_schedulable':'True', 'env':'infra'}" openshift_schedulable=True
104.211.154.71 openshift_node_labels="{'logging':'True', 'openshift_schedulable':'True', 'env':'infra'}" openshift_schedulable=True

[nfs]
104.211.154.71
